const SET_CURRENT_USER = "SET_CURRENT_USER"
const CLEAR_CURRENT_USER = "CLEAR_CURRENT_USER"
const GET_REPORTS = "GET_REPORTS"
const ADD_REPORT = "ADD_REPORT"
const EDIT_REPORT = "EDIT_REPORT"
const DELETE_REPORT = "DELETE_REPORT"
const SET_SELECTED_REPORT = "SET_SELECTED_REPORT"
const UNSET_REPORT = "UNSET_REPORT"
const FILTERS_FORM_CHANGE = "FILTERS_FORM_CHANGE"
const BEGIN_AUTH = "BEGIN_AUTH"
const COMPLETE_AUTH = "COMPLETE_AUTH"

export {
  SET_CURRENT_USER,
  CLEAR_CURRENT_USER,
  GET_REPORTS,
  ADD_REPORT,
  EDIT_REPORT,
  DELETE_REPORT,
  SET_SELECTED_REPORT,
  UNSET_REPORT,
  FILTERS_FORM_CHANGE,
 BEGIN_AUTH,
  COMPLETE_AUTH
}